{
  "formatVersion": "1.1",
  "component": {
    "group": "solutions.dreamforge.krawler",
    "module": "krawler",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0-beta"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-metadata-0.0.1.jar",
          "url": "krawler-0.0.1.jar",
          "size": 31705,
          "sha512": "682ac77dae23209d062e5120d12a2ad3440a89fcac2d85b36b42331718e5bfd2c5c70116c87e3ba9a044063c792821a9d2795df3600f56700b7c2786ac29722b",
          "sha256": "16613288767492d02dd458969e18cf8391f5ed5e939ca82b1858456bbf18bc03",
          "sha1": "91f417ebf7f2366a04c9f33d60963fc3b7d1bc87",
          "md5": "59beafccaa1edc591f1caa3ab0b72fa2"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "krawler-kotlin-0.0.1-sources.jar",
          "url": "krawler-0.0.1-sources.jar",
          "size": 37081,
          "sha512": "566b5d382d61eb1573f9d17c8fc15eaa5fc7dab7e09a86508446d140b051e5e08de35abdac4b962b5ebe44d60d0f8d6c90efb994a4c7a9e162b21ff274321c0e",
          "sha256": "463ec2cf7bc09ff5acfd3a5d44b2e03033b9f9dd37d89969503c56fc96e7bfca",
          "sha1": "4cd6294ece938c0a2ba0be240f4f44463bfe03e8",
          "md5": "6dccfc3916178ba70eb1865b834917e9"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../krawler-android/0.0.1/krawler-android-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../krawler-android/0.0.1/krawler-android-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../krawler-android/0.0.1/krawler-android-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-android",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iosarm64/0.0.1/krawler-iosarm64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iosarm64/0.0.1/krawler-iosarm64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iosarm64/0.0.1/krawler-iosarm64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iosarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iossimulatorarm64/0.0.1/krawler-iossimulatorarm64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iossimulatorarm64/0.0.1/krawler-iossimulatorarm64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iossimulatorarm64/0.0.1/krawler-iossimulatorarm64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iossimulatorarm64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iosx64/0.0.1/krawler-iosx64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iosx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iosx64/0.0.1/krawler-iosx64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iosx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../krawler-iosx64/0.0.1/krawler-iosx64-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-iosx64",
        "version": "0.0.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../krawler-js/0.0.1/krawler-js-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../krawler-js/0.0.1/krawler-js-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../krawler-js/0.0.1/krawler-js-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../krawler-jvm/0.0.1/krawler-jvm-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../krawler-jvm/0.0.1/krawler-jvm-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../krawler-jvm/0.0.1/krawler-jvm-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-jvm",
        "version": "0.0.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../krawler-wasm-js/0.0.1/krawler-wasm-js-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-wasm-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../krawler-wasm-js/0.0.1/krawler-wasm-js-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-wasm-js",
        "version": "0.0.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../krawler-wasm-js/0.0.1/krawler-wasm-js-0.0.1.module",
        "group": "solutions.dreamforge.krawler",
        "module": "krawler-wasm-js",
        "version": "0.0.1"
      }
    }
  ]
}
