{
  "formatVersion": "1.1",
  "component": {
    "url": "../../krawler/0.0.2/krawler-0.0.2.module",
    "group": "solutions.dreamforge.krawler",
    "module": "krawler",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-wasm-js-0.0.2.klib",
          "url": "krawler-wasm-js-0.0.2.klib",
          "size": 253185,
          "sha512": "daaf61f3b3a0e040c6a17ae8f2869fb956bd726c8f5a0721584286d100e3e697381d62e0aa1ebde09df5590aae1e5bfee4556bbbb669ff3242af07b3cd12e112",
          "sha256": "2e4713a61aeb0de7e0e82d72e63647ed1dea44ce0a5fed5cff814f25dbc23b42",
          "sha1": "c0a2b3617f6c4a964e8f696744222ea4e6796080",
          "md5": "79e92861a926b8343063213fecec32ff"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-wasm-js-0.0.2.klib",
          "url": "krawler-wasm-js-0.0.2.klib",
          "size": 253185,
          "sha512": "daaf61f3b3a0e040c6a17ae8f2869fb956bd726c8f5a0721584286d100e3e697381d62e0aa1ebde09df5590aae1e5bfee4556bbbb669ff3242af07b3cd12e112",
          "sha256": "2e4713a61aeb0de7e0e82d72e63647ed1dea44ce0a5fed5cff814f25dbc23b42",
          "sha1": "c0a2b3617f6c4a964e8f696744222ea4e6796080",
          "md5": "79e92861a926b8343063213fecec32ff"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "krawler-wasm-js-0.0.2-sources.jar",
          "url": "krawler-wasm-js-0.0.2-sources.jar",
          "size": 36913,
          "sha512": "fbf72ed13abe5742abd6e993d329b0c6c7c781b95ca471ba622a5f16ce84c539e7f8c952ba6f52cddf813a703717e271f56dd049902ff7c67559787e62c45152",
          "sha256": "9cfc95f25b2f076c0edb7cdda994d29e84641a502db105dff412101039c90e4e",
          "sha1": "acfd4c465a4f9ef0ee9d7487407f61ca50e4654d",
          "md5": "51d9c9087244d0ecfdc30cfa602b17c7"
        }
      ]
    }
  ]
}
