{
  "formatVersion": "1.1",
  "component": {
    "url": "../../krawler/0.0.1/krawler-0.0.1.module",
    "group": "solutions.dreamforge.krawler",
    "module": "krawler",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0-beta"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-iosX64Main-0.0.1.klib",
          "url": "krawler-iosx64-0.0.1.klib",
          "size": 270228,
          "sha512": "e2f697f8a78d7d6aee39efb2ec28a4aa098c8879f88a89229dc40f5d0958716b50cc4a5481f5ff358bde9f769b42cf3fe224585ad649bb205260d389498e73ca",
          "sha256": "a283510e6e31534f81455a1a342f449e6c17c996c7ad07b52b487ad4b736daa3",
          "sha1": "45e6c880438aa8d8716fa10bc35f9c29d002c9a8",
          "md5": "cbf3b356f5dbfdd5e18a7b93cd3bc562"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "krawler-iosx64-0.0.1-sources.jar",
          "url": "krawler-iosx64-0.0.1-sources.jar",
          "size": 37081,
          "sha512": "756281b5b1e01370095fe94fe3ce4c0288661d18dd38313f76a820f5982a53531c4e66ffc27ee175031a868448027bd0c5a5820276451e0191d6153b39e17739",
          "sha256": "2c32f42c51d0a124cb0bd8c2589294d13a7fcabb9d14bc891e095dae8ad01214",
          "sha1": "7a6dc47752d771479653a993bd41b55e1ef42d00",
          "md5": "468f379d2b01c53d6d6909a7eb598f6e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0-beta"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.28.0-beta"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-iosx64-0.0.1-metadata.jar",
          "url": "krawler-iosx64-0.0.1-metadata.jar",
          "size": 3295,
          "sha512": "8f6ad108b07cb7392afd4f9bfe0ccef5f4c8ad79cabea9ebf246e93c2cd4c8c4cf85c67dc1adc2bea586f8f350a86b50e1f61774a3cdadde4f2fefe5b77d69df",
          "sha256": "d20d595a27f5d4f93893040c1793407d9b6fa99b6c887a86f60080daba009259",
          "sha1": "e5cf2600397877387c7114f5747812bd3418e045",
          "md5": "105032905129aaa569f6b1ad2017ada2"
        }
      ]
    }
  ]
}
