{
  "formatVersion": "1.1",
  "component": {
    "url": "../../krawler/0.0.2/krawler-0.0.2.module",
    "group": "solutions.dreamforge.krawler",
    "module": "krawler",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-jvm-0.0.2.jar",
          "url": "krawler-jvm-0.0.2.jar",
          "size": 405987,
          "sha512": "a93d54d7e9fdd110ecfba170ea8fce2cba74c064d771cb4d66ee9973d25b74e6cffd9dca47cf7fed0d8f2b9fe882164555425887b56fdd71fd1ecb673eb198c5",
          "sha256": "c1293930ee1c7f9b92c136a5a62d2319f61c7243239afbfaff84d6bcad73e54e",
          "sha1": "afef6216c5769167364f72062d2e8570ae74c06f",
          "md5": "e3af36a6a2dfa9831ed592f8ee79bd62"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-swing",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "com.github.crawler-commons",
          "module": "crawler-commons",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.typesafe",
          "module": "config",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-jvm-0.0.2.jar",
          "url": "krawler-jvm-0.0.2.jar",
          "size": 405987,
          "sha512": "a93d54d7e9fdd110ecfba170ea8fce2cba74c064d771cb4d66ee9973d25b74e6cffd9dca47cf7fed0d8f2b9fe882164555425887b56fdd71fd1ecb673eb198c5",
          "sha256": "c1293930ee1c7f9b92c136a5a62d2319f61c7243239afbfaff84d6bcad73e54e",
          "sha1": "afef6216c5769167364f72062d2e8570ae74c06f",
          "md5": "e3af36a6a2dfa9831ed592f8ee79bd62"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "krawler-jvm-0.0.2-sources.jar",
          "url": "krawler-jvm-0.0.2-sources.jar",
          "size": 37002,
          "sha512": "f3685650634e5244608c96a2983940e035cefb5d58a20eb2b7c8556ad37488679ec290cc03e0d2b1ab632e2c51f34be6742fe74840c84396a016810786ee5ae5",
          "sha256": "e86013b0c0331398e21b3256522c9bb33aa121765f783887cfc330090b403855",
          "sha1": "dd7b497662d9562d6d4b0473b9e710e3b777a44e",
          "md5": "0cad9e6296f23eed9f13aedad844d8cc"
        }
      ]
    }
  ]
}
