{
  "formatVersion": "1.1",
  "component": {
    "url": "../../krawler/0.0.2/krawler-0.0.2.module",
    "group": "solutions.dreamforge.krawler",
    "module": "krawler",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-js-0.0.2.klib",
          "url": "krawler-js-0.0.2.klib",
          "size": 253539,
          "sha512": "b9dfebe00bf301b33e7ee2617a881e4715bfdef09b800072c9835a9dd59a63d4a50fff0504d03c6feb5ff5ec2ced2c87fce301dc7dde9f03ceb058b5a4470acb",
          "sha256": "5f6cb2f6f8ce0063a98fa93e303323d897a1b52c8e58b23df5e4406938f25db7",
          "sha1": "13ac0b52fd5e585fbcb1820fcaa5993beffc6e59",
          "md5": "f90051e94aaca43a187a540b23d44c21"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-js",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.1.3"
          }
        },
        {
          "group": "com.fleeksoft.ksoup",
          "module": "ksoup",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "io.github.reactivecircus.cache4k",
          "module": "cache4k",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.29.0"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-concurrent-collections",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "krawler-js-0.0.2.klib",
          "url": "krawler-js-0.0.2.klib",
          "size": 253539,
          "sha512": "b9dfebe00bf301b33e7ee2617a881e4715bfdef09b800072c9835a9dd59a63d4a50fff0504d03c6feb5ff5ec2ced2c87fce301dc7dde9f03ceb058b5a4470acb",
          "sha256": "5f6cb2f6f8ce0063a98fa93e303323d897a1b52c8e58b23df5e4406938f25db7",
          "sha1": "13ac0b52fd5e585fbcb1820fcaa5993beffc6e59",
          "md5": "f90051e94aaca43a187a540b23d44c21"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "krawler-js-0.0.2-sources.jar",
          "url": "krawler-js-0.0.2-sources.jar",
          "size": 36833,
          "sha512": "bd3c3390033e5e32c9c20b1a3c4b8b53ead02adcb7d9cdb8013c4f66a1b75e385b3d7e6e238dfe30811cba2946589dea9f5350b1a66589460486330aa998bb3c",
          "sha256": "399f641fe9751ca8999b814ccdacb003f94f8eca352c2bdfa70723093ca81c82",
          "sha1": "6ceccf0ed3165993cf8f5bc4cbef809d05426ed4",
          "md5": "c523ff5cc2b466ca868b3b16bac83222"
        }
      ]
    }
  ]
}
